# Generated by Django 4.0.4 on 2022-04-18 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='relator',
            new_name='realtor',
        ),
    ]
